---
version: "3.7"
services:
  mkdocs:
    image: ghcr.io/som-energia/somenergia-poetry-docker-workshop-mkdocs:latest
    build:
      context: ./services/mkdocs/
      dockerfile: Dockerfile
    container_name: mkdocs
    ports:
      - "8000:8000"
    volumes:
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./docs:/docs/docs
      - .git:/docs/.git:ro # needed for plugins
