[tool.poetry]
name = "part-1"
version = "0.1.0"
description = ""
authors = ["you <you@mail.something>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
